### ISSUE TITLE
An example of a new version is needed

### ISSUE THREAD

**Issue by icandura** [AkashiSN/ffmpeg-docker#5]
I was using the 4.4.2-qsv version of the image. Use it like sample
```
$ docker run --rm -it --device=/dev/dri -v `pwd`:/workdir \
  akashisn/ffmpeg:4.4-qsv -y \
    -init_hw_device qsv=qsv:hw -hwaccel qsv -filter_hw_device qsv -hwaccel_output_format qsv \
    -fflags +discardcorrupt \
    -analyzeduration 10M -probesize 32M \
    -i AB1.m2ts \
    -t 30 \
    -c:v h264_qsv \
    -global_quality 20 \
    -vf hwupload=extra_hw_frames=64,vpp_qsv=deinterlace=2,scale_qsv=1920:-1,fps=30000/1001 \
    -c:a aac -ar 48000 -ab 256k \
    -f mp4 \
    AB1_h264_qsv.mp4
```
But when I upgraded to version 5.1.2-qsv, it didn't work with the example.
The error message is 
```
Error initializing an MFX session: -4.
Device creation failed: -1313558101.
Failed to set value 'qsv=qsv:hw' for option 'init_hw_device': Unknown error occurred
Error parsing global options: Unknown error occurred
```
Could you please give us a sample for new version?

**Comment by AkashiSN** [comment]
Thank you for the issue.

Upon checking, the QSV build was broken, so I have fixed it. Also, I have changed it to use libvpl instead of libmfx in ffmpeg 6.0. Due to the delay-loading of the dynamic library, we were able to achieve a pseudo-static link, so we have stopped tagging with `qsv` and consolidated the tags. We have updated the sample example where QSV can be used.

Please check and confirm. Thank you.

**Comment by icandura** [comment]
Thanks for the reply. I'm sorry I didn't see this thread sooner. 
I think it was my previous system version that was too old (Debian 9). In the last few days, I installed a Debian 12, with the latest 6.0 image and it worked successfully with the example you provided.
